# Generated by Django 4.2.10 on 2024-02-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=20)),
                ('fileName', models.CharField(default='', max_length=50)),
                ('createdTimeStamp', models.TimeField(auto_now_add=True)),
                ('fileExtention', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
